apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: my-flask-app
        image: public.ecr.aws/x6f2f4a8/mbitionproject:1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000