apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: my-flask-app
        image: ananya1101/mbitionproject:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: my-flask-app
  namespace: default
spec:
  selector:
    app: my-flask-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service
      targetPort: 8000  # Port on which your Flask application is running