apiVersion: v1
kind: Service
metadata:
  name: my-flask-app
  namespace: default
spec:
  selector:
    app: my-flask-app
  
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service
      targetPort: 8000  # Port on which your Flask application is running
  type: LoadBalancer